server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_pro?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
